apiVersion: v1
kind: Service
metadata:
  name: {{ .sts_name }}
  namespace: {{ .sts_namespace }}
  labels:
    tabtabai.com/tabclaw: "true"
    tabtabai.com/tabclaw-name: {{ .sts_name }}
spec:
  ports:
  - port: 18789
    name: gateway
    protocol: TCP
    targetPort: port1
  - port: 18790
    name: another
    protocol: TCP
    targetPort: port2
  selector:
    tabtabai.com/tabclaw: "true"
    tabtabai.com/tabclaw-name: {{ .sts_name }}
